# Generated by Django 3.2.7 on 2021-10-19 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.DecimalField(decimal_places=5, help_text='Azimuth in degrees', max_digits=8)),
                ('elevation', models.DecimalField(decimal_places=6, help_text='Elevation in degrees', max_digits=8)),
            ],
            options={
                'unique_together': {('azimuth', 'elevation')},
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, unique=True)),
                ('file', models.OneToOneField(help_text='The FITS file this Session data was pulled from', on_delete=django.db.models.deletion.CASCADE, to='rfi.file')),
                ('project', models.ForeignKey(help_text='The Project this Session belongs to', on_delete=django.db.models.deletion.CASCADE, to='rfi.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('mjd', models.DecimalField(db_index=True, decimal_places=3, max_digits=8)),
                ('lst', models.DecimalField(decimal_places=7, max_digits=9)),
                ('resolution', models.DecimalField(decimal_places=10, max_digits=11)),
                ('exposure', models.DecimalField(decimal_places=5, max_digits=8)),
                ('tsys', models.DecimalField(decimal_places=4, max_digits=6)),
                ('unit', models.TextField()),
                ('backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.backend')),
                ('coordinates', models.ForeignKey(help_text='The averaged(?) location on the sky this scan took place', on_delete=django.db.models.deletion.CASCADE, to='rfi.coordinates')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.feed')),
                ('frequency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.frequencytype')),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.frontend')),
                ('polarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.polarization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.session')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.source')),
            ],
            options={
                'unique_together': {('session', 'number', 'mjd')},
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='frontend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.frontend'),
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.PositiveIntegerField()),
                ('channel', models.PositiveIntegerField()),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField(help_text='Intensity in Jy')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi.scan')),
            ],
            options={
                'unique_together': {('scan', 'channel', 'frequency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('number', 'frontend')},
        ),
    ]
