# Generated by Django 3.2.7 on 2021-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
