# Generated by Django 3.2.25 on 2024-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0004_frequency_is_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='view_level_0',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='view_level_1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='view_level_2',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='frequency',
            field=models.FloatField(db_index=True),
        ),
    ]
