# Generated by Django 3.2.25 on 2024-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0006_auto_20240715_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='view_level_0',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='view_level_1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='frequency',
            name='view_level_2',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
