# Generated by Django 3.2.25 on 2024-07-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0007_auto_20240715_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='is_peak',
        ),
    ]
