# Generated by Django 3.2.25 on 2024-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi', '0008_remove_frequency_is_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='view_level_3',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
